AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECR template
Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
        RepositoryName: "nginxdemos/hello"
        ImageScanningConfiguration: 
            scanOnPush: "true"
        Tags:
          - Key: "Creator"
            Value: "YanmDemo"
