AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECR template
Parameters:
  RepoName:
    Type: String
    Default: nginxdemos/hello
    Description: The private repository name for nginx demo.
Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
        RepositoryName: !Ref RepoName
        ImageScanningConfiguration: 
            scanOnPush: "false"
        Tags:
          - Key: "Creator"
            Value: "YanmDemo"
